version: '3.9'
services:
    web:
        build: 
            context: .
            target: production
        env_file:
            - ./.env
        ports:
            - "4000:5000"
        volumes:
            - ./todo_app:/app/todo_app
        environment: 
            PORT: 4000
            FLASK_DEBUG: 1  